export const COUNTRIES = [
  {name:"India",code:"+91",iso:"IN"},{name:"United States",code:"+1",iso:"US"},{name:"United Kingdom",code:"+44",iso:"GB"},
  {name:"Canada",code:"+1",iso:"CA"},{name:"Australia",code:"+61",iso:"AU"},{name:"Germany",code:"+49",iso:"DE"},
  {name:"France",code:"+33",iso:"FR"},{name:"Japan",code:"+81",iso:"JP"},{name:"Singapore",code:"+65",iso:"SG"},
  {name:"United Arab Emirates",code:"+971",iso:"AE"},{name:"Netherlands",code:"+31",iso:"NL"},{name:"Italy",code:"+39",iso:"IT"},
  {name:"Spain",code:"+34",iso:"ES"},{name:"Brazil",code:"+55",iso:"BR"},{name:"Mexico",code:"+52",iso:"MX"},
  {name:"South Korea",code:"+82",iso:"KR"},{name:"Thailand",code:"+66",iso:"TH"},{name:"Malaysia",code:"+60",iso:"MY"},
  {name:"Indonesia",code:"+62",iso:"ID"},{name:"New Zealand",code:"+64",iso:"NZ"},{name:"South Africa",code:"+27",iso:"ZA"},
  {name:"Sweden",code:"+46",iso:"SE"},{name:"Norway",code:"+47",iso:"NO"},{name:"Denmark",code:"+45",iso:"DK"},
  {name:"Switzerland",code:"+41",iso:"CH"},{name:"China",code:"+86",iso:"CN"},{name:"Hong Kong",code:"+852",iso:"HK"},
  {name:"Philippines",code:"+63",iso:"PH"},{name:"Vietnam",code:"+84",iso:"VN"},{name:"Ireland",code:"+353",iso:"IE"},
  {name:"Belgium",code:"+32",iso:"BE"},{name:"Austria",code:"+43",iso:"AT"},{name:"Portugal",code:"+351",iso:"PT"},
  {name:"Poland",code:"+48",iso:"PL"},{name:"Greece",code:"+30",iso:"GR"},{name:"Israel",code:"+972",iso:"IL"},
  {name:"Saudi Arabia",code:"+966",iso:"SA"},{name:"Qatar",code:"+974",iso:"QA"},{name:"Oman",code:"+968",iso:"OM"},
  {name:"Bahrain",code:"+973",iso:"BH"},{name:"Kuwait",code:"+965",iso:"KW"},{name:"Egypt",code:"+20",iso:"EG"},
  {name:"Turkey",code:"+90",iso:"TR"},{name:"Russia",code:"+7",iso:"RU"},{name:"Sri Lanka",code:"+94",iso:"LK"},
  {name:"Nepal",code:"+977",iso:"NP"},{name:"Bangladesh",code:"+880",iso:"BD"},{name:"Maldives",code:"+960",iso:"MV"},
  {name:"Taiwan",code:"+886",iso:"TW"},{name:"Pakistan",code:"+92",iso:"PK"},{name:"Argentina",code:"+54",iso:"AR"},
  {name:"Colombia",code:"+57",iso:"CO"},{name:"Chile",code:"+56",iso:"CL"},{name:"Peru",code:"+51",iso:"PE"},
  {name:"Finland",code:"+358",iso:"FI"},{name:"Czech Republic",code:"+420",iso:"CZ"},{name:"Romania",code:"+40",iso:"RO"},
  {name:"Hungary",code:"+36",iso:"HU"},{name:"Kenya",code:"+254",iso:"KE"},{name:"Nigeria",code:"+234",iso:"NG"},
];

export const COUNTRY_NAMES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
  'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
  'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
  'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria',
  'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
  'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
  'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark',
  'Djibouti', 'Dominica', 'Dominican Republic', 'DR Congo', 'Ecuador', 'Egypt',
  'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
  'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
  'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
  'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
  'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
  'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
  'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
  'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia',
  'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
  'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea',
  'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
  'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
  'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
  'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
  'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
  'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
  'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
  'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo',
  'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
  'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
  'Yemen', 'Zambia', 'Zimbabwe',
];
